baseURL = "https://andyjgao.com/"
title = "AndyJGao"
copyright = "© Andy J. Gao, 2020"
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-XXXX"
DisqusShortname = ""
theme = "hugo-theme-chunky-poster"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
   [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 2
  # [[menu.main]]
  #   identifier = "about"
  #   name = "About"
  #   url = "/about/"
  #   weight = 3

[taxonomies]
category = "categories"
tag = "tags"

[params]
  author = "Andy J Gao"
  description = "Lorem ipsum dolor sit amet."
  homepageImage = "/images/prof_pic.jpg"
  share = false
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = false
    email = ""
    facebook = ""
    twitter = "https://twitter.com/andyjgao"
    linkedin = ""
    stack-overflow = ""
    instagram = ""
    github = "https://github.com/andyjgao"
    weibo = ""
    medium = ""
    pinterest = ""
    reddit = ""
    gitlab = ""
    mastodon = ""
    keybase = ""

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
