baseURL = "https://andyjgao.com/"
title = "AndyJGao"
copyright = ""
paginate = 2
languageCode = "en"
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"
googleAnalytics = "UA-162644416-1"
DisqusShortname = ""
theme = "hugo-theme-chunky-poster"
summaryLength = 30
[menu]
  # [[menu.main]]
  #   identifier = "home"
  #   name = "Home"
  #   url = "/"
  #   weight = 1
   [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog/"
    weight = 1
  [[menu.main]]
    identifier = "notes"
    name = "Notes"
    url = "/notes/"
    weight = 2
  [[menu.main]]
    identifier = "mail"
    name = "Mail"
    url = "https://mondaymail.substack.com/"
    weight = 3

[taxonomies]
category = "categories"
tag = "tags"

[params]
  author = "Andy J Gao"
  description = "Hi, I'm Andy Gao. I write about Tech, Entrepreneurship, Lifestyle, and Productivity. I like slow walks on the beach."
  homepageImage = "/images/prof_pic.jpg"
  share = false
  showLanguageSwitcher = false

  # Custom CSS and JS. Relative to /static/css and /static/js respectively.
  customCSS = []
  customJS = []

  [params.social]
    rss = false
    email = ""
    facebook = ""
    twitter = "https://twitter.com/andyjgao"
    linkedin = ""
    stack-overflow = ""
    instagram = ""
    github = "https://github.com/andyjgao"
    weibo = ""
    medium = ""
    pinterest = ""
    reddit = ""
    gitlab = ""
    mastodon = ""
    keybase = ""

  [params.prismJS]
    enable = true
    theme = ""

  [params.commento]
    enable = true
    url = "https://commento.io"

[markup]
  [markup.highlight]
    codeFences = false

[services]
  [services.instagram]
    disableInlineCSS = true

  [services.twitter]
    disableInlineCSS = true
